2024-12-09 18:39:58,379 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.30.53:44391'
2024-12-09 18:39:59,827 - distributed.worker - INFO -       Start worker at:     tcp://10.0.30.53:41831
2024-12-09 18:39:59,827 - distributed.worker - INFO -          Listening to:     tcp://10.0.30.53:41831
2024-12-09 18:39:59,827 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-12-09 18:39:59,827 - distributed.worker - INFO -          dashboard at:           10.0.30.53:37663
2024-12-09 18:39:59,827 - distributed.worker - INFO - Waiting to connect to:     tcp://10.0.30.56:34911
2024-12-09 18:39:59,827 - distributed.worker - INFO - -------------------------------------------------
2024-12-09 18:39:59,827 - distributed.worker - INFO -               Threads:                          1
2024-12-09 18:39:59,827 - distributed.worker - INFO -                Memory:                   4.66 GiB
2024-12-09 18:39:59,827 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-a7nyqqxe
2024-12-09 18:39:59,828 - distributed.worker - INFO - -------------------------------------------------
2024-12-09 18:40:01,569 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-12-09 18:40:01,570 - distributed.worker - INFO -         Registered to:     tcp://10.0.30.56:34911
2024-12-09 18:40:01,570 - distributed.worker - INFO - -------------------------------------------------
2024-12-09 18:40:01,571 - distributed.core - INFO - Starting established connection to tcp://10.0.30.56:34911
2024-12-09 19:04:09,773 - distributed.core - INFO - Connection to tcp://10.0.30.56:34911 has been closed.
2024-12-09 19:04:09,794 - distributed.worker - INFO - Stopping worker at tcp://10.0.30.53:41831. Reason: worker-handle-scheduler-connection-broken
2024-12-09 19:04:09,796 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/Net/Groups/BGI/scratch/crobin/miniconda3/envs/ExtremesEnv2/lib/python3.12/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.0.30.53:38362 remote=tcp://10.0.30.56:34911>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-12-09 19:04:09,808 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.0.30.53:44391'. Reason: worker-handle-scheduler-connection-broken
2024-12-09 19:04:09,809 - distributed.worker - INFO - Removing Worker plugin shuffle
2024-12-09 19:04:09,813 - distributed.nanny - INFO - Worker closed
2024-12-09 19:04:11,815 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-12-09 19:04:12,227 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.30.53:44391'. Reason: nanny-close-gracefully
2024-12-09 19:04:12,228 - distributed.nanny - INFO - Nanny at 'tcp://10.0.30.53:44391' closed.
2024-12-09 19:04:12,228 - distributed.dask_worker - INFO - End worker
